/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Fran
 */
public class CONSULTA extends javax.swing.JFrame {
    Principal objPrincipal = new Principal ();

    /**
     * Creates new form CONSULTA
     */
    public CONSULTA() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.setTitle("Consultar dona");
        CBOMARCA.addItem(objPrincipal.marca0);
        CBOMARCA.addItem(objPrincipal.marca1);
        CBOMARCA.addItem(objPrincipal.marca2);
        CBOMARCA.addItem(objPrincipal.marca3);
        CBOMARCA.addItem(objPrincipal.marca4);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LBLPRECIO = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        CBOMARCA = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        LBLCONTENIDO = new javax.swing.JLabel();
        LBLPESO = new javax.swing.JLabel();
        LBLSABOR = new javax.swing.JLabel();
        BTNCERRAR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LBLPRECIO.setText("lbl1");

        jLabel2.setText("Precio (s./)");

        jLabel3.setText("Contenido (und.)");

        jLabel4.setText("Peso (gr.)");

        jLabel5.setText("Sabor");

        CBOMARCA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBOMARCAActionPerformed(evt);
            }
        });

        jLabel6.setText("Marca");

        LBLCONTENIDO.setText("lbl2");

        LBLPESO.setText("lbl3");

        LBLSABOR.setText("lbl4");

        BTNCERRAR.setText("Cerrar");
        BTNCERRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCERRARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LBLCONTENIDO)
                            .addComponent(LBLPESO)
                            .addComponent(LBLSABOR)
                            .addComponent(LBLPRECIO)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(114, 114, 114)
                        .addComponent(CBOMARCA, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(BTNCERRAR, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(CBOMARCA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNCERRAR, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(LBLPRECIO))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(LBLCONTENIDO))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LBLPESO)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(LBLSABOR))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CBOMARCAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBOMARCAActionPerformed
        // TODO add your handling code here:
        if (CBOMARCA.getSelectedItem()==objPrincipal.marca0)
        {
            LBLPRECIO.setText(Double.toString(objPrincipal.precio0));
            LBLCONTENIDO.setText(Integer.toString(objPrincipal.contenido0));
            LBLPESO.setText(Double.toString(objPrincipal.peso0));
            LBLSABOR.setText(objPrincipal.sabor0);
        }
        else
            if (CBOMARCA.getSelectedItem()==objPrincipal.marca1)
        {
            LBLPRECIO.setText(Double.toString(objPrincipal.precio1));
            LBLCONTENIDO.setText(Integer.toString(objPrincipal.contenido1));
            LBLPESO.setText(Double.toString(objPrincipal.peso1));
            LBLSABOR.setText(objPrincipal.sabor1);
        } 
            else
                if (CBOMARCA.getSelectedItem()==objPrincipal.marca2)
        {
            LBLPRECIO.setText(Double.toString(objPrincipal.precio2));
            LBLCONTENIDO.setText(Integer.toString(objPrincipal.contenido2));
            LBLPESO.setText(Double.toString(objPrincipal.peso2));
            LBLSABOR.setText(objPrincipal.sabor2);
        }
        else
                    if (CBOMARCA.getSelectedItem()==objPrincipal.marca3)
        {
            LBLPRECIO.setText(Double.toString(objPrincipal.precio3));
            LBLCONTENIDO.setText(Integer.toString(objPrincipal.contenido3));
            LBLPESO.setText(Double.toString(objPrincipal.peso3));
            LBLSABOR.setText(objPrincipal.sabor3);
        }
        else
                        if (CBOMARCA.getSelectedItem()==objPrincipal.marca4)
        {
            LBLPRECIO.setText(Double.toString(objPrincipal.precio4));
            LBLCONTENIDO.setText(Integer.toString(objPrincipal.contenido4));
            LBLPESO.setText(Double.toString(objPrincipal.peso4));
            LBLSABOR.setText(objPrincipal.sabor4);
        } 
    }//GEN-LAST:event_CBOMARCAActionPerformed

    private void BTNCERRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCERRARActionPerformed
        // TODO add your handling code here:
        objPrincipal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BTNCERRARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CONSULTA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CONSULTA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CONSULTA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CONSULTA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CONSULTA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNCERRAR;
    private javax.swing.JComboBox<String> CBOMARCA;
    private javax.swing.JLabel LBLCONTENIDO;
    private javax.swing.JLabel LBLPESO;
    private javax.swing.JLabel LBLPRECIO;
    private javax.swing.JLabel LBLSABOR;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
