/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Fran
 */
public class LISTAR extends javax.swing.JFrame {
Principal objPrincipal= new Principal();
    /**
     * Creates new form LISTAR
     */
    public LISTAR() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.setTitle("Listar Donas");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BTNCERRAR = new javax.swing.JButton();
        BTNLISTAR = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TXTAREALISTAR = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BTNCERRAR.setText("Cerrar");
        BTNCERRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCERRARActionPerformed(evt);
            }
        });

        BTNLISTAR.setText("Listar");
        BTNLISTAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNLISTARActionPerformed(evt);
            }
        });

        TXTAREALISTAR.setColumns(20);
        TXTAREALISTAR.setRows(5);
        jScrollPane2.setViewportView(TXTAREALISTAR);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(BTNCERRAR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BTNLISTAR)
                .addGap(100, 100, 100))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNCERRAR)
                    .addComponent(BTNLISTAR))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNCERRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCERRARActionPerformed
        // TODO add your handling code here:
        objPrincipal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BTNCERRARActionPerformed

    private void BTNLISTARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNLISTARActionPerformed
        // TODO add your handling code here:
        TXTAREALISTAR.append("    LISTADO DE DONAS"+"\n\n");
        TXTAREALISTAR.append("Marca:  "+objPrincipal.marca0+"\n");
        TXTAREALISTAR.append("Precio:  "+objPrincipal.precio0+"\n");
        TXTAREALISTAR.append("Contenido:  "+objPrincipal.contenido0+"\n");
        TXTAREALISTAR.append("Peso:  "+objPrincipal.peso0+"\n");
        TXTAREALISTAR.append("Sabor:  "+objPrincipal.sabor0+"\n\n");
        TXTAREALISTAR.append("Marca:  "+objPrincipal.marca1+"\n");
        TXTAREALISTAR.append("Precio:  "+objPrincipal.precio1+"\n");
        TXTAREALISTAR.append("Contenido:  "+objPrincipal.contenido1+"\n");
        TXTAREALISTAR.append("Peso:  "+objPrincipal.peso1+"\n");
        TXTAREALISTAR.append("Sabor:  "+objPrincipal.sabor1+"\n\n");
        TXTAREALISTAR.append("Marca:  "+objPrincipal.marca2+"\n");
        TXTAREALISTAR.append("Precio:  "+objPrincipal.precio2+"\n");
        TXTAREALISTAR.append("Contenido:  "+objPrincipal.contenido2+"\n");
        TXTAREALISTAR.append("Peso:  "+objPrincipal.peso2+"\n");
        TXTAREALISTAR.append("Sabor:  "+objPrincipal.sabor2+"\n\n");
        TXTAREALISTAR.append("Marca:  "+objPrincipal.marca3+"\n");
        TXTAREALISTAR.append("Precio:  "+objPrincipal.precio3+"\n");
        TXTAREALISTAR.append("Contenido:  "+objPrincipal.contenido3+"\n");
        TXTAREALISTAR.append("Peso:  "+objPrincipal.peso3+"\n");
        TXTAREALISTAR.append("Sabor:  "+objPrincipal.sabor3+"\n\n");
        TXTAREALISTAR.append("Marca:  "+objPrincipal.marca4+"\n");
        TXTAREALISTAR.append("Precio:  "+objPrincipal.precio4+"\n");
        TXTAREALISTAR.append("Contenido:  "+objPrincipal.contenido4+"\n");
        TXTAREALISTAR.append("Peso:  "+objPrincipal.peso4+"\n");
        TXTAREALISTAR.append("Sabor:  "+objPrincipal.sabor4+"\n\n");
    }//GEN-LAST:event_BTNLISTARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LISTAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LISTAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LISTAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LISTAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LISTAR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNCERRAR;
    private javax.swing.JButton BTNLISTAR;
    private javax.swing.JTextArea TXTAREALISTAR;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
