/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Fran
 */
public class MODIFICAR extends javax.swing.JFrame {
Principal objPrincipal = new Principal ();
    /**
     * Creates new form MODIFICAR
     */
    public MODIFICAR() {
        initComponents();
         this.setLocationRelativeTo(this);
        this.setTitle("Modificar dona");
        CBOMARCA.addItem(objPrincipal.marca0);
        CBOMARCA.addItem(objPrincipal.marca1);
        CBOMARCA.addItem(objPrincipal.marca2);
        CBOMARCA.addItem(objPrincipal.marca3);
        CBOMARCA.addItem(objPrincipal.marca4);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        CBOMARCA = new javax.swing.JComboBox<>();
        TXTPRECIO = new javax.swing.JTextField();
        TXTCONTENIDO = new javax.swing.JTextField();
        TXTPESO = new javax.swing.JTextField();
        TXTSABOR = new javax.swing.JTextField();
        BTNCERRAR = new javax.swing.JButton();
        BTNGRABAR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Marca");

        jLabel2.setText("Precio (s/.)");

        jLabel3.setText("Contenido(und.)");

        jLabel4.setText("Peso(gr.)");

        jLabel5.setText("Sabor");

        CBOMARCA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBOMARCAActionPerformed(evt);
            }
        });

        TXTPRECIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTPRECIOActionPerformed(evt);
            }
        });

        TXTCONTENIDO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTCONTENIDOActionPerformed(evt);
            }
        });

        TXTPESO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTPESOActionPerformed(evt);
            }
        });

        BTNCERRAR.setText("Cerrar");
        BTNCERRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCERRARActionPerformed(evt);
            }
        });

        BTNGRABAR.setText("Grabar");
        BTNGRABAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNGRABARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TXTPRECIO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXTCONTENIDO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXTPESO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXTSABOR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBOMARCA, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTNCERRAR)
                    .addComponent(BTNGRABAR))
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CBOMARCA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNCERRAR))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TXTPRECIO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNGRABAR))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TXTCONTENIDO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TXTPESO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TXTSABOR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNCERRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCERRARActionPerformed
        // TODO add your handling code here:
        objPrincipal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BTNCERRARActionPerformed

    private void CBOMARCAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBOMARCAActionPerformed
        // TODO add your handling code here:
        if (CBOMARCA.getSelectedItem()==objPrincipal.marca0)
        {
            TXTPRECIO.setText(Double.toString(objPrincipal.precio0));
            TXTCONTENIDO.setText(Integer.toString(objPrincipal.contenido0));
            TXTPESO.setText(Double.toString(objPrincipal.peso0));
            TXTSABOR.setText(objPrincipal.sabor0);
        }
        else
            if (CBOMARCA.getSelectedItem()==objPrincipal.marca1)
        {
            TXTPRECIO.setText(Double.toString(objPrincipal.precio1));
            TXTCONTENIDO.setText(Integer.toString(objPrincipal.contenido1));
            TXTPESO.setText(Double.toString(objPrincipal.peso1));
            TXTSABOR.setText(objPrincipal.sabor1);
        } 
            else
                if (CBOMARCA.getSelectedItem()==objPrincipal.marca2)
        {
            TXTPRECIO.setText(Double.toString(objPrincipal.precio2));
            TXTCONTENIDO.setText(Integer.toString(objPrincipal.contenido2));
            TXTPESO.setText(Double.toString(objPrincipal.peso2));
            TXTSABOR.setText(objPrincipal.sabor2);
        }
        else
                    if (CBOMARCA.getSelectedItem()==objPrincipal.marca3)
        {
            TXTPRECIO.setText(Double.toString(objPrincipal.precio3));
            TXTCONTENIDO.setText(Integer.toString(objPrincipal.contenido3));
            TXTPESO.setText(Double.toString(objPrincipal.peso3));
            TXTSABOR.setText(objPrincipal.sabor3);
        }
        else
                        if (CBOMARCA.getSelectedItem()==objPrincipal.marca4)
        {
            TXTPRECIO.setText(Double.toString(objPrincipal.precio4));
            TXTCONTENIDO.setText(Integer.toString(objPrincipal.contenido4));
            TXTPESO.setText(Double.toString(objPrincipal.peso4));
            TXTSABOR.setText(objPrincipal.sabor4);
        } 
    }//GEN-LAST:event_CBOMARCAActionPerformed

    private void TXTCONTENIDOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTCONTENIDOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTCONTENIDOActionPerformed

    private void TXTPRECIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTPRECIOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTPRECIOActionPerformed

    private void TXTPESOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTPESOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTPESOActionPerformed

    private void BTNGRABARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNGRABARActionPerformed
        // TODO add your handling code here:
         if(CBOMARCA.getSelectedItem()==objPrincipal.marca0)
        {
            objPrincipal.precio0=Double.parseDouble(TXTPRECIO.getText());
            objPrincipal.contenido0=Integer.parseInt(TXTCONTENIDO.getText());
            objPrincipal.peso0=Double.parseDouble(TXTPESO.getText());
            objPrincipal.sabor0=TXTSABOR.getText();
        }
        else
            if(CBOMARCA.getSelectedItem()==objPrincipal.marca1)
            {
                objPrincipal.precio1=Double.parseDouble(TXTPRECIO.getText());
                objPrincipal.contenido1=Integer.parseInt(TXTCONTENIDO.getText());
                objPrincipal.peso1=Double.parseDouble(TXTPESO.getText());
                objPrincipal.sabor1=TXTSABOR.getText();
            }
         else
            if(CBOMARCA.getSelectedItem()==objPrincipal.marca2)
        {
            objPrincipal.precio2=Double.parseDouble(TXTPRECIO.getText());
            objPrincipal.contenido2=Integer.parseInt(TXTCONTENIDO.getText());
            objPrincipal.peso2=Double.parseDouble(TXTPESO.getText());
            objPrincipal.sabor2=TXTSABOR.getText();
        }
        else
            if(CBOMARCA.getSelectedItem()==objPrincipal.marca3)
            {
                objPrincipal.precio3=Double.parseDouble(TXTPRECIO.getText());
                objPrincipal.contenido3=Integer.parseInt(TXTCONTENIDO.getText());
                objPrincipal.peso3=Double.parseDouble(TXTPESO.getText());
                objPrincipal.sabor3=TXTSABOR.getText();
                }
            else
                {
                objPrincipal.precio4=Double.parseDouble(TXTPRECIO.getText());
                objPrincipal.contenido4=Integer.parseInt(TXTCONTENIDO.getText());
                objPrincipal.peso4=Double.parseDouble(TXTPESO.getText());
                objPrincipal.sabor4=TXTSABOR.getText();
                }
    }//GEN-LAST:event_BTNGRABARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MODIFICAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MODIFICAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MODIFICAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MODIFICAR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MODIFICAR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNCERRAR;
    private javax.swing.JButton BTNGRABAR;
    private javax.swing.JComboBox<String> CBOMARCA;
    private javax.swing.JTextField TXTCONTENIDO;
    private javax.swing.JTextField TXTPESO;
    private javax.swing.JTextField TXTPRECIO;
    private javax.swing.JTextField TXTSABOR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
